// Type-ahead suggestions for the search-filter autocompletes. These only assist
// entry — users can still type any custom value (allowCustom on the inputs).

export const LOCATION_SUGGESTIONS: string[] = [
  'Remote',
  // Major U.S. tech hubs (city, state)
  'San Francisco, CA',
  'San Jose, CA',
  'Palo Alto, CA',
  'Mountain View, CA',
  'Sunnyvale, CA',
  'Santa Clara, CA',
  'Cupertino, CA',
  'Los Angeles, CA',
  'San Diego, CA',
  'Seattle, WA',
  'Bellevue, WA',
  'Redmond, WA',
  'Portland, OR',
  'New York, NY',
  'Brooklyn, NY',
  'Boston, MA',
  'Cambridge, MA',
  'Austin, TX',
  'Dallas, TX',
  'Houston, TX',
  'Chicago, IL',
  'Atlanta, GA',
  'Denver, CO',
  'Boulder, CO',
  'Washington, DC',
  'Arlington, VA',
  'Reston, VA',
  'Pittsburgh, PA',
  'Philadelphia, PA',
  'Raleigh, NC',
  'Durham, NC',
  'Charlotte, NC',
  'Miami, FL',
  'Phoenix, AZ',
  'Salt Lake City, UT',
  'Minneapolis, MN',
  'Detroit, MI',
  'Ann Arbor, MI',
  'Nashville, TN',
  'Madison, WI',
  // States (broad matches)
  'California',
  'Washington',
  'New York',
  'Texas',
  'Massachusetts',
  'Illinois',
  'Georgia',
  'Colorado',
  'Virginia',
  'Florida',
  'Pennsylvania',
  'North Carolina',
];

export const COMPANY_SUGGESTIONS: string[] = [
  'Google', 'Meta', 'Amazon', 'Apple', 'Microsoft', 'Netflix', 'Nvidia', 'Intel',
  'IBM', 'Oracle', 'Salesforce', 'Adobe', 'Cisco', 'Qualcomm', 'AMD', 'Dell',
  'Uber', 'Lyft', 'Airbnb', 'Tesla', 'SpaceX', 'PayPal', 'Stripe', 'Snap',
  'Pinterest', 'LinkedIn', 'TikTok', 'ByteDance', 'Spotify', 'Atlassian',
  'ServiceNow', 'Workday', 'Snowflake', 'Databricks', 'Palantir', 'Twilio',
  'Shopify', 'DoorDash', 'Instacart', 'Robinhood', 'Coinbase', 'Datadog',
  'Cloudflare', 'JPMorgan Chase', 'Goldman Sachs', 'Morgan Stanley',
  'Capital One', 'Visa', 'Mastercard', 'Fidelity', 'BlackRock', 'Deloitte',
  'Accenture', 'Boeing', 'Lockheed Martin', 'Northrop Grumman', 'Raytheon',
  'General Motors', 'Ford', 'Honeywell', 'Medtronic', 'Intuit', 'eBay',
  'Dropbox', 'Zoom', 'Okta', 'Splunk', 'MongoDB', 'Roblox', 'Electronic Arts',
  'Activision', 'Siemens', 'Bosch',
];
